environment: production
title: Hexcore
email:
description: >- # this means to ignore newlines until "baseurl:"
  Hexcore is advanced framework based on NestJs to build hexagonal architecture designed apps
baseurl: "/hexcore"
url: "https://mararok.github.io"
twitter_username:
github_username:  mararok


theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

footer_content: "Copyright &copy; 2021 Mararok"
