environment: production
title: Hexcore
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hexcore is advanced framework based on NestJs to build hexagonal architecture designed apps
baseurl: "/hexcore"
url: "https://mararok.github.io"
github_username:  mararok

theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed

include: ['_pages']

footer_content: "Copyright &copy; 2021-2022 Mararok"